name: 'Setup TTA Development Environment'
description: 'Install uv and configure Python environment for TTA.dev'
author: 'TTA.dev Team'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

runs:
  using: 'composite'
  steps:
    - name: Cache uv binary
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/uv
        key: ${{ runner.os }}-uv-0.5.x

    - name: Install uv (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        if ! command -v uv &> /dev/null; then
          echo "Installing uv..."
          curl -LsSf https://astral.sh/uv/install.sh | sh
        else
          echo "uv already installed"
        fi

    - name: Install uv (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        if (!(Get-Command uv -ErrorAction SilentlyContinue)) {
          Write-Output "Installing uv..."
          irm https://astral.sh/uv/install.ps1 | iex
        } else {
          Write-Output "uv already installed"
        }

    - name: Add uv to PATH (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Add uv to PATH (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: echo "$env:USERPROFILE\.cargo\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Verify uv installation
      shell: bash
      run: |
        uv --version
        echo "✅ uv successfully installed and available"

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          .venv
        key: ${{ runner.os }}-python-${{ inputs.python-version }}-${{ hashFiles('uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-python-${{ inputs.python-version }}-
          ${{ runner.os }}-python-
