import os

def link_orphans_to_hub():
    """
    Appends a link to the Project Hub to all orphaned Logseq pages.
    """
    orphaned_files = [
        "logseq/pages/AI Agents.md",
        "logseq/pages/AI Engineers.md",
        "logseq/pages/API.md",
        "logseq/pages/Active.md",
        "logseq/pages/Agent Skills Development.md",
        "logseq/pages/AnthropicPrimitive.md",
        "logseq/pages/Architects.md",
        "logseq/pages/Architecture.md",
        "logseq/pages/Backend Developers.md",
        "logseq/pages/CachePrimitive.md",
        "logseq/pages/Complete.md",
        "logseq/pages/ConditionalPrimitive.md",
        "logseq/pages/Contributors.md",
        "logseq/pages/Core Primitives.md",
        "logseq/pages/Core.md",
        "logseq/pages/Database.md",
        "logseq/pages/DevOps.md",
        "logseq/pages/Developers.md",
        "logseq/pages/Docker.md",
        "logseq/pages/Documentation.md",
        "logseq/pages/Example TODO.md",
        "logseq/pages/Example.md",
        "logseq/pages/Examples.md",
        "logseq/pages/Experimental.md",
        "logseq/pages/FallbackPrimitive.md",
        "logseq/pages/Gemini CLI Integration.md",
        "logseq/pages/GitHub.md",
        "logseq/pages/High.md",
        "logseq/pages/How-To.md",
        "logseq/pages/Infrastructure.md",
        "logseq/pages/InstrumentedPrimitive.md",
        "logseq/pages/Logseq Features.md",
        "logseq/pages/Logseq Knowledge Base.md",
        "logseq/pages/Low.md",
        "logseq/pages/MCP.md",
        "logseq/pages/Medium.md",
        "logseq/pages/Multi-Agent Orchestration.md",
        "logseq/pages/New Users.md",
        "logseq/pages/OllamaPrimitive.md",
        "logseq/pages/OpenAIPrimitive.md",
        "logseq/pages/Package.md",
        "logseq/pages/Page Reference.md",
        "logseq/pages/ParallelPrimitive.md",
        "logseq/pages/Performance Optimization.md",
        "logseq/pages/Performance.md",
        "logseq/pages/Phase 2 Integration Tests.md",
        "logseq/pages/Phase 9 Content Backfill Strategy.md",
        "logseq/pages/Primitive.md",
        "logseq/pages/Primitive1.md",
        "logseq/pages/Primitive2.md",
        "logseq/pages/Production.md",
        "logseq/pages/Python.md",
        "logseq/pages/Recovery Patterns.md",
        "logseq/pages/Recovery.md",
        "logseq/pages/RetryPrimitive.md",
        "logseq/pages/RouterPrimitive.md",
        "logseq/pages/Senior Developers.md",
        "logseq/pages/SequentialPrimitive.md",
        "logseq/pages/Session Context___ CachePrimitive.md",
        "logseq/pages/Stable.md",
        "logseq/pages/TODO System Quickstart.md",
        "logseq/pages/TTA KB Automation___LinkValidator.md",
        "logseq/pages/TTA KB Automation___SessionContextBuilder.md",
        "logseq/pages/TTA KB Automation___TODO Sync.md",
        "logseq/pages/TTA Primitives___CachePrimitive.md",
        "logseq/pages/TTA Primitives___CompensationPrimitive.md",
        "logseq/pages/TTA Primitives___ConditionalPrimitive.md",
        "logseq/pages/TTA Primitives___FallbackPrimitive.md",
        "logseq/pages/TTA Primitives___KnowledgeBasePrimitive.md",
        "logseq/pages/TTA Primitives___ParallelPrimitive.md",
        "logseq/pages/TTA Primitives___RetryPrimitive.md",
        "logseq/pages/TTA Primitives___SequentialPrimitive.md",
        "logseq/pages/TTA Primitives___TimeoutPrimitive.md",
        "logseq/pages/TTA Primitives___WorkflowPrimitive.md",
        "logseq/pages/TTA.dev (Meta-Project).md",
        "logseq/pages/TTA.dev.md",
        "logseq/pages/TTA.dev___Agent Instruction System.md",
        "logseq/pages/TTA.dev___Architecture.md",
        "logseq/pages/TTA.dev___Architecture___Agent Discoverability.md",
        "logseq/pages/TTA.dev___Architecture___Component Integration.md",
        "logseq/pages/TTA.dev___Architecture___Observability Assessment.md",
        "logseq/pages/TTA.dev___Architecture___Observability Executive Summary.md",
        "logseq/pages/TTA.dev___Architecture___Observability Implementation.md",
        "logseq/pages/TTA.dev___Atomic DevOps Architecture.md",
        "logseq/pages/TTA.dev___Best Practices___Agentic Testing.md",
        "logseq/pages/TTA.dev___Best Practices___Deployment.md",
        "logseq/pages/TTA.dev___Best Practices___Testing.md",
        "logseq/pages/TTA.dev___CI-CD Pipeline.md",
        "logseq/pages/TTA.dev___Common Mistakes___Testing Antipatterns.md",
        "logseq/pages/TTA.dev___Common.md",
        "logseq/pages/TTA.dev___Concepts___Composition.md",
        "logseq/pages/TTA.dev___DevOps Studio Architecture.md",
        "logseq/pages/TTA.dev___DevOps Studio___Infrastructure as Code.md",
        "logseq/pages/TTA.dev___DevOps Studio___Monitoring Stack.md",
        "logseq/pages/TTA.dev___Examples.md",
        "logseq/pages/TTA.dev___Examples___Basic Workflow.md",
        "logseq/pages/TTA.dev___Examples___Cost Tracking Workflow.md",
        "logseq/pages/TTA.dev___Examples___Multi-Agent Workflow.md",
        "logseq/pages/TTA.dev___Examples___Overview.md",
        "logseq/pages/TTA.dev___Examples___RAG Workflow.md",
        "logseq/pages/TTA.dev___Guides.md",
        "logseq/pages/TTA.dev___Guides___Agentic Primitives.md",
        "logseq/pages/TTA.dev___Guides___Architecture Patterns.md",
        "logseq/pages/TTA.dev___Guides___Beginner Quickstart.md",
        "logseq/pages/TTA.dev___Guides___Context Management.md",
        "logseq/pages/TTA.dev___Guides___Copilot Toolsets.md",
        "logseq/pages/TTA.dev___Guides___Cost Optimization.md",
        "logseq/pages/TTA.dev___Guides___Database Selection.md",
        "logseq/pages/TTA.dev___Guides___Error Handling Patterns.md",
        "logseq/pages/TTA.dev___Guides___First Workflow.md",
        "logseq/pages/TTA.dev___Guides___Getting Started.md",
        "logseq/pages/TTA.dev___Guides___Integration Primitives.md",
        "logseq/pages/TTA.dev___Guides___LLM Selection.md",
        "logseq/pages/TTA.dev___Guides___Observability.md",
        "logseq/pages/TTA.dev___Guides___Orchestration Configuration.md",
        "logseq/pages/TTA.dev___Guides___Production Deployment.md",
        "logseq/pages/TTA.dev___Guides___Testing Workflows.md",
        "logseq/pages/TTA.dev___Guides___Workflow Composition.md",
        "logseq/pages/TTA.dev___How-To___Building Reliable AI Workflows.md",
        "logseq/pages/TTA.dev___How-To___Custom Primitive Development.md",
        "logseq/pages/TTA.dev___How-To___Debugging Workflows.md",
        "logseq/pages/TTA.dev___How-To___Integrating External Services.md",
        "logseq/pages/TTA.dev___How-To___Performance Tuning.md",
        "logseq/pages/TTA.dev___Integration___AI Libraries Comparison.md",
        "logseq/pages/TTA.dev___Integration___AI Libraries Integration Plan.md",
        "logseq/pages/TTA.dev___Integration___Transformers.md",
        "logseq/pages/TTA.dev___MCP___AI Assistant Guide.md",
        "logseq/pages/TTA.dev___MCP___Integration.md",
        "logseq/pages/TTA.dev___Migration Dashboard.md",
        "logseq/pages/TTA.dev___Milestones___v1.0.0 Production Release.md",
        "logseq/pages/TTA.dev___Observability.md",
        "logseq/pages/TTA.dev___Packages___keploy-framework.md",
        "logseq/pages/TTA.dev___Packages___python-pathway.md",
        "logseq/pages/TTA.dev___Packages___tta-dev-primitives.md",
        "logseq/pages/TTA.dev___Packages___tta-kb-automation.md",
        "logseq/pages/TTA.dev___Packages___tta-observability-integration.md",
        "logseq/pages/TTA.dev___Packages___universal-agent-context.md",
        "logseq/pages/TTA.dev___Patterns___Caching.md",
        "logseq/pages/TTA.dev___Patterns___Error Handling.md",
        "logseq/pages/TTA.dev___Patterns___Sequential Workflow.md",
        "logseq/pages/TTA.dev___Primitives Catalog.md",
        "logseq/pages/TTA.dev___Primitives.md",
        "logseq/pages/TTA.dev___Primitives___InstrumentedPrimitive.md",
        "logseq/pages/TTA.dev___Stage Guides___Development Stage.md",
        "logseq/pages/TTA.dev___Stage Guides___Testing Stage.md",
        "logseq/pages/TTA.dev___Strategy___Gap Analysis Response.md",
        "logseq/pages/TTA.dev___Templates.md",
        "logseq/pages/TTA.dev___Testing.md",
        "logseq/pages/Testing & Quality.md",
        "logseq/pages/Testing.md",
        "logseq/pages/TimeoutPrimitive.md",
        "logseq/pages/Topic Page.md",
        "logseq/pages/Whiteboard - Agentic Development Workflow.md",
        "logseq/pages/Whiteboard - Primitive Composition Patterns.md",
        "logseq/pages/Whiteboard - TODO Dependency Network.md",
        "logseq/pages/Whiteboard - Testing Architecture.md",
        "logseq/pages/Workflow.md",
        "logseq/pages/WorkflowContext.md",
        "logseq/pages/WorkflowPrimitive.md",
        "logseq/pages/Workflow___Test.md",
        "logseq/pages/tta-dev-primitives.md",
        "logseq/pages/tta-observability-integration.md",
    ]

    for orphan in orphaned_files:
        if os.path.exists(orphan):
            with open(orphan, "a") as f:
                f.write("\n- [[Project Hub]]")
            print(f"Linked {orphan} to Project Hub.")
        else:
            print(f"Warning: {orphan} not found.")

if __name__ == "__main__":
    link_orphans_to_hub()
