# This file should be placed in TTA-notes/.github/workflows/sync-to-tta-dev.yml
# It triggers the reverse sync workflow in TTA.dev

name: Trigger TTA.dev Sync

on:
  # Run on push to main when TTA.dev pages change
  push:
    branches: [main]
    paths:
      - 'logseq/pages/TTA.dev/**'
      - 'logseq/journals/TTA.dev/**'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  trigger-tta-dev-sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger TTA.dev sync workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TTA_DEV_PAT }}
          repository: theinterneti/TTA.dev
          event-type: sync-to-tta-dev
          client-payload: |
            {
              "source_repo": "TTA-notes",
              "source_commit": "${{ github.sha }}",
              "triggered_by": "${{ github.actor }}"
            }
      
      - name: Create dispatch summary
        if: success()
        run: |
          echo "✅ Triggered TTA.dev sync workflow"
          echo "TTA.dev will create a PR with the changes"

