"""Markdown-based observability - zero config, git-friendly."""

from datetime import datetime
from pathlib import Path
from typing import Any


class MarkdownObservabilityLogger:
    """Logs TTA.dev activity to markdown files that auto-grow."""

    def __init__(self, log_dir: str = ".tta/logs"):
        self.log_dir = Path(log_dir)
        self.log_dir.mkdir(parents=True, exist_ok=True)

        # Create index if it doesn't exist
        self.index_file = self.log_dir / "INDEX.md"
        if not self.index_file.exists():
            self._create_index()

    def _create_index(self):
        """Create the main index page."""
        self.index_file.write_text(
            """# TTA.dev Activity Log

This directory contains auto-generated logs of TTA.dev usage.

## Quick Links
- [Primitives Used](primitives.md)
- [Workflows Executed](workflows.md)
- [Agents Activated](agents.md)
- [Today's Activity](activity-{date}.md)

---
*Auto-generated by TTA.dev observability*
""".format(date=datetime.now().strftime("%Y-%m-%d"))
        )

    def log_primitive_use(self, primitive_name: str, context: dict[str, Any]):
        """Log when a primitive is used."""
        file = self.log_dir / "primitives.md"
        timestamp = datetime.now().isoformat()

        # Append to primitives log using append mode (safe for concurrent writes)
        entry = f"\n## {primitive_name}\n"
        entry += f"- **Time**: {timestamp}\n"
        entry += f"- **Context**: {context.get('workflow_id', 'N/A')}\n"

        if not file.exists():
            file.write_text(f"# Primitives Used\n")
        
        with open(file, "a") as f:
            f.write(entry)

    def log_workflow_execution(self, workflow_name: str, status: str, duration_ms: float):
        """Log workflow execution."""
        file = self.log_dir / "workflows.md"
        timestamp = datetime.now().isoformat()

        entry = f"\n## {workflow_name}\n"
        entry += f"- **Time**: {timestamp}\n"
        entry += f"- **Status**: {status}\n"
        entry += f"- **Duration**: {duration_ms:.2f}ms\n"

        if file.exists():
            content = file.read_text()
            file.write_text(content + entry)
        else:
            file.write_text(f"# Workflows Executed\n{entry}")

    def log_agent_activity(self, agent_name: str, action: str):
        """Log agent activity."""
        file = self.log_dir / "agents.md"
        timestamp = datetime.now().isoformat()

        entry = f"\n## {agent_name}\n"
        entry += f"- **Time**: {timestamp}\n"
        entry += f"- **Action**: {action}\n"

        if file.exists():
            content = file.read_text()
            file.write_text(content + entry)
        else:
            file.write_text(f"# Agents Activated\n{entry}")

    def log_daily_activity(self, event: str, details: dict[str, Any]):
        """Log to today's activity file."""
        date = datetime.now().strftime("%Y-%m-%d")
        file = self.log_dir / f"activity-{date}.md"
        timestamp = datetime.now().strftime("%H:%M:%S")

        entry = f"\n### {timestamp} - {event}\n"
        for key, value in details.items():
            entry += f"- **{key}**: {value}\n"

        if not file.exists():
            file.write_text(f"# Activity Log - {date}\n")
        
        with open(file, "a") as f:
            f.write(entry)


# Global singleton
_logger = None


def get_logger() -> MarkdownObservabilityLogger:
    """Get or create the global markdown logger."""
    global _logger
    if _logger is None:
        _logger = MarkdownObservabilityLogger()
    return _logger
