"""Markdown-based observability logger.

Logs workflow execution, primitive usage, and agent activity to markdown files.
Simple, git-friendly, human-readable observability without background services.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from ttadev.primitives.adaptive.base import WorkflowContext


class MarkdownLogger:
    """Logs observability data to markdown files."""
    
    def __init__(self, log_dir: Path | str = ".tta/logs"):
        """Initialize markdown logger.
        
        Args:
            log_dir: Directory for markdown logs (default: .tta/logs)
        """
        self.log_dir = Path(log_dir)
        self.log_dir.mkdir(parents=True, exist_ok=True)
        
    def log_workflow_start(self, workflow_id: str, workflow_name: str, context: WorkflowContext) -> None:
        """Log workflow execution start."""
        log_file = self.log_dir / "workflows.md"
        timestamp = datetime.now().isoformat()
        
        entry = f"""
## Workflow: {workflow_name}
- **ID**: `{workflow_id}`
- **Started**: {timestamp}
- **Context**: {json.dumps(context.metadata, indent=2)}

"""
        self._append_to_file(log_file, entry)
        
    def log_primitive_usage(self, primitive_name: str, input_data: Any, output_data: Any, duration_ms: float) -> None:
        """Log primitive usage."""
        log_file = self.log_dir / "primitives.md"
        timestamp = datetime.now().isoformat()
        
        entry = f"""
### {primitive_name}
- **Time**: {timestamp}
- **Duration**: {duration_ms:.2f}ms
- **Input**: `{self._truncate(str(input_data))}`
- **Output**: `{self._truncate(str(output_data))}`

"""
        self._append_to_file(log_file, entry)
        
    def log_agent_activity(self, agent_name: str, action: str, details: dict[str, Any]) -> None:
        """Log agent activity."""
        log_file = self.log_dir / "agents.md"
        timestamp = datetime.now().isoformat()
        
        entry = f"""
## Agent: {agent_name}
- **Time**: {timestamp}
- **Action**: {action}
- **Details**:
  ```json
  {json.dumps(details, indent=2)}
  ```

"""
        self._append_to_file(log_file, entry)
        
    def _append_to_file(self, file_path: Path, content: str) -> None:
        """Append content to file, creating with header if needed."""
        if not file_path.exists():
            header = f"# {file_path.stem.title()} Log\n\nGenerated by TTA.dev\n"
            file_path.write_text(header)
        
        with file_path.open("a", encoding="utf-8") as f:
            f.write(content)
            
    def _truncate(self, text: str, max_len: int = 100) -> str:
        """Truncate long strings."""
        return text if len(text) <= max_len else f"{text[:max_len]}..."


# Global logger instance
_logger = MarkdownLogger()


def log_workflow_start(workflow_id: str, workflow_name: str, context: WorkflowContext) -> None:
    """Log workflow start (convenience function)."""
    _logger.log_workflow_start(workflow_id, workflow_name, context)


def log_primitive_usage(primitive_name: str, input_data: Any, output_data: Any, duration_ms: float) -> None:
    """Log primitive usage (convenience function)."""
    _logger.log_primitive_usage(primitive_name, input_data, output_data, duration_ms)


def log_agent_activity(agent_name: str, action: str, details: dict[str, Any]) -> None:
    """Log agent activity (convenience function)."""
    _logger.log_agent_activity(agent_name, action, details)
