version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
      - "1234:1234"
      - "7687:7687"
    env_file:
      - .env  # Replace with your actual environment variables
    volumes:
      - .:/app  # Mount the current directory to /app in the container
      - com.docker.devenvironments.code:/app/tta.prod  
    working_dir: /app
    command: /bin/sh -c "./setup.sh"
