"""Well-known cloud model catalog for ModelRegistryPrimitive.

This module contains the pre-populated cloud model entries and provider-specific
model ID lists. Extracted from model_registry.py to keep the behavioral primitive
focused and the data catalog independently maintainable.
"""

from __future__ import annotations

from ttadev.primitives.llm.model_registry import ModelEntry

# ── Well-known cloud models ───────────────────────────────────────────────────

_DEFAULT_CLOUD_MODELS: list[ModelEntry] = [
    # ── Groq (free tier, high-throughput) ─────────────────────────────────────
    ModelEntry(
        model_id="llama-3.3-70b-versatile",
        provider="groq",
        display_name="Llama 3.3 70B Versatile (Groq)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="llama-3.1-70b-versatile",
        provider="groq",
        display_name="Llama 3.1 70B Versatile (Groq)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="llama-3.1-8b-instant",
        provider="groq",
        display_name="Llama 3.1 8B Instant (Groq)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="llama3-8b-8192",
        provider="groq",
        display_name="Llama 3 8B (Groq)",
        context_length=8_192,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="llama3-70b-8192",
        provider="groq",
        display_name="Llama 3 70B (Groq)",
        context_length=8_192,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="meta-llama/llama-4-scout-17b-16e-instruct",
        provider="groq",
        display_name="Llama 4 Scout 17B (Groq)",
        context_length=131_072,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="gemma-7b-it",
        provider="groq",
        display_name="Gemma 7B IT (Groq)",
        context_length=8_192,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="moonshotai/kimi-k2-instruct",
        provider="groq",
        display_name="Kimi K2 Instruct (Groq)",
        context_length=131_072,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="qwen/qwen3-32b",
        provider="groq",
        display_name="Qwen3 32B (Groq) — thinking model",
        context_length=32_768,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"thinking_model": True},
    ),
    ModelEntry(
        model_id="compound-beta",
        provider="groq",
        display_name="Compound Beta (Groq)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"compound_model": True},
    ),
    ModelEntry(
        model_id="openai/gpt-oss-20b",
        provider="groq",
        display_name="GPT-OSS 20B (Groq)",
        context_length=8_192,
        supports_tool_calling=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="openai/gpt-oss-120b",
        provider="groq",
        display_name="GPT-OSS 120B (Groq)",
        context_length=8_192,
        supports_tool_calling=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="meta-llama/llama-4-maverick-17b-128e-instruct",
        provider="groq",
        display_name="Llama 4 Maverick 17B (Groq)",
        context_length=131_072,
        supports_tool_calling=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    # ── Gemini (models/ prefix for OpenAI-compat endpoint) ────────────────────
    ModelEntry(
        model_id="models/gemini-2.5-flash",
        provider="google",
        display_name="Gemini 2.5 Flash",
        context_length=1_048_576,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="low",
        is_local=False,
    ),
    ModelEntry(
        model_id="models/gemini-2.5-pro",
        provider="google",
        display_name="Gemini 2.5 Pro",
        context_length=1_048_576,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="medium",
        is_local=False,
    ),
    ModelEntry(
        model_id="models/gemini-2.0-flash",
        provider="google",
        display_name="Gemini 2.0 Flash",
        context_length=1_048_576,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="low",
        is_local=False,
    ),
    ModelEntry(
        model_id="models/gemini-2.0-flash-lite",
        provider="google",
        display_name="Gemini 2.0 Flash Lite",
        context_length=1_048_576,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    # Gemini 1.5 models were removed by Google (404). Use ProviderModelDiscovery.for_google()
    # for current model list.
    # ── Google Gemma (via Google AI Studio — same GOOGLE_API_KEY as Gemini) ────
    # 14,400 RPD / 30 RPM / 15K TPM — much higher RPD than Gemini frontier models.
    ModelEntry(
        model_id="gemma-3-27b-it",
        provider="google",
        display_name="Gemma 3 27B (Google AI Studio)",
        context_length=131_072,
        supports_tool_calling=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "30 RPM / 14,400 RPD / 15K TPM. Same GOOGLE_API_KEY as Gemini."},
    ),
    ModelEntry(
        model_id="gemma-3-12b-it",
        provider="google",
        display_name="Gemma 3 12B (Google AI Studio)",
        context_length=131_072,
        supports_tool_calling=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "30 RPM / 14,400 RPD / 15K TPM. Same GOOGLE_API_KEY as Gemini."},
    ),
    ModelEntry(
        model_id="gemma-3-4b-it",
        provider="google",
        display_name="Gemma 3 4B (Google AI Studio)",
        context_length=131_072,
        supports_tool_calling=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "30 RPM / 14,400 RPD / 15K TPM. Same GOOGLE_API_KEY as Gemini."},
    ),
    ModelEntry(
        model_id="gemma-3-1b-it",
        provider="google",
        display_name="Gemma 3 1B (Google AI Studio)",
        context_length=32_768,
        supports_tool_calling=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "30 RPM / 14,400 RPD / 15K TPM. Same GOOGLE_API_KEY as Gemini."},
    ),
    # ── GitHub Models (free tier — requires GITHUB_TOKEN, 50–150 req/day) ──────
    ModelEntry(
        model_id="gpt-5",
        provider="github",
        display_name="GPT-5 (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. 10 RPM / 50 RPD."},
    ),
    ModelEntry(
        model_id="gpt-5-mini",
        provider="github",
        display_name="GPT-5 Mini (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. 15 RPM / 150 RPD."},
    ),
    ModelEntry(
        model_id="gpt-4.1",
        provider="github",
        display_name="GPT-4.1 (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. 10 RPM / 50 RPD."},
    ),
    ModelEntry(
        model_id="gpt-4.1-mini",
        provider="github",
        display_name="GPT-4.1 Mini (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. 15 RPM / 150 RPD."},
    ),
    ModelEntry(
        model_id="gpt-4o",
        provider="github",
        display_name="GPT-4o (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API (GITHUB_TOKEN). 10 RPM / 50 RPD."},
    ),
    ModelEntry(
        model_id="gpt-4o-mini",
        provider="github",
        display_name="GPT-4o Mini (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. 15 RPM / 150 RPD."},
    ),
    ModelEntry(
        model_id="o3",
        provider="github",
        display_name="o3 (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. 10 RPM / 50 RPD.", "thinking_model": True},
    ),
    ModelEntry(
        model_id="o4-mini",
        provider="github",
        display_name="o4-mini (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. 15 RPM / 150 RPD.", "thinking_model": True},
    ),
    ModelEntry(
        model_id="Llama-4-Scout-17B-16E-Instruct",
        provider="github",
        display_name="Llama 4 Scout 17B (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. 10 RPM / 50 RPD."},
    ),
    ModelEntry(
        model_id="Llama-4-Maverick-17B-128E-Instruct",
        provider="github",
        display_name="Llama 4 Maverick 17B (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. 10 RPM / 50 RPD."},
    ),
    ModelEntry(
        model_id="Meta-Llama-3.3-70B-Instruct",
        provider="github",
        display_name="Llama 3.3 70B (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. 10 RPM / 50 RPD."},
    ),
    ModelEntry(
        model_id="Meta-Llama-3.1-405B-Instruct",
        provider="github",
        display_name="Llama 3.1 405B (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. 10 RPM / 50 RPD."},
    ),
    ModelEntry(
        model_id="Meta-Llama-3.1-8B-Instruct",
        provider="github",
        display_name="Llama 3.1 8B (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. 15 RPM / 150 RPD."},
    ),
    ModelEntry(
        model_id="DeepSeek-V3-0324",
        provider="github",
        display_name="DeepSeek V3 0324 (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. 10 RPM / 50 RPD."},
    ),
    ModelEntry(
        model_id="DeepSeek-R1-0528",
        provider="github",
        display_name="DeepSeek R1 0528 (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. 10 RPM / 50 RPD.", "thinking_model": True},
    ),
    ModelEntry(
        model_id="DeepSeek-R1",
        provider="github",
        display_name="DeepSeek R1 (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. Strong reasoning.", "thinking_model": True},
    ),
    ModelEntry(
        model_id="grok-3",
        provider="github",
        display_name="Grok 3 (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. 10 RPM / 50 RPD."},
    ),
    ModelEntry(
        model_id="grok-3-mini",
        provider="github",
        display_name="Grok 3 Mini (GitHub Models)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. 15 RPM / 150 RPD."},
    ),
    ModelEntry(
        model_id="Phi-4-mini-instruct",
        provider="github",
        display_name="Phi-4 Mini Instruct (GitHub Models)",
        context_length=16_000,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. Microsoft Phi-4 Mini."},
    ),
    ModelEntry(
        model_id="Phi-4-multimodal-instruct",
        provider="github",
        display_name="Phi-4 Multimodal (GitHub Models)",
        context_length=16_000,
        supports_tool_calling=False,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. Microsoft Phi-4 multimodal."},
    ),
    ModelEntry(
        model_id="Phi-4",
        provider="github",
        display_name="Phi-4 (GitHub Models)",
        context_length=16_000,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"notes": "Free via GitHub Models API. Microsoft Phi-4."},
    ),
    # ── OpenRouter free models (:free suffix) ─────────────────────────────────
    ModelEntry(
        model_id="mistralai/mistral-7b-instruct:free",
        provider="openrouter",
        display_name="Mistral 7B Instruct Free (OpenRouter)",
        context_length=32_768,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="microsoft/phi-3-mini-128k-instruct:free",
        provider="openrouter",
        display_name="Phi-3 Mini 128K Free (OpenRouter)",
        context_length=128_000,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="meta-llama/llama-3.2-3b-instruct:free",
        provider="openrouter",
        display_name="Llama 3.2 3B Instruct Free (OpenRouter)",
        context_length=131_072,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="meta-llama/llama-3.1-8b-instruct:free",
        provider="openrouter",
        display_name="Llama 3.1 8B Instruct Free (OpenRouter)",
        context_length=131_072,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="google/gemma-3-27b-it:free",
        provider="openrouter",
        display_name="Gemma 3 27B IT Free (OpenRouter)",
        context_length=131_072,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="qwen/qwen3-30b-a3b:free",
        provider="openrouter",
        display_name="Qwen3 30B A3B Free (OpenRouter)",
        context_length=40_960,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="deepseek/deepseek-r1:free",
        provider="openrouter",
        display_name="DeepSeek R1 Free (OpenRouter) — thinking model",
        context_length=163_840,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
        metadata={"thinking_model": True, "strip_thinking": True},
    ),
    ModelEntry(
        model_id="meta-llama/llama-3.3-70b-instruct:free",
        provider="openrouter",
        display_name="Llama 3.3 70B Instruct Free (OpenRouter)",
        context_length=131_072,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="google/gemma-3-12b-it:free",
        provider="openrouter",
        display_name="Gemma 3 12B IT Free (OpenRouter)",
        context_length=131_072,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="google/gemma-3-4b-it:free",
        provider="openrouter",
        display_name="Gemma 3 4B IT Free (OpenRouter)",
        context_length=131_072,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="mistralai/mistral-small-3.1-24b-instruct:free",
        provider="openrouter",
        display_name="Mistral Small 3.1 24B Free (OpenRouter)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="openai/gpt-oss-120b:free",
        provider="openrouter",
        display_name="GPT-OSS 120B Free (OpenRouter)",
        context_length=8_192,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="openai/gpt-oss-20b:free",
        provider="openrouter",
        display_name="GPT-OSS 20B Free (OpenRouter)",
        context_length=8_192,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    # ── Together AI ───────────────────────────────────────────────────────────
    ModelEntry(
        model_id="meta-llama/Llama-3.2-3B-Instruct-Turbo",
        provider="together",
        display_name="Llama 3.2 3B Instruct Turbo (Together)",
        context_length=131_072,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="low",
        is_local=False,
    ),
    ModelEntry(
        model_id="meta-llama/Llama-3.3-70B-Instruct-Turbo",
        provider="together",
        display_name="Llama 3.3 70B Instruct Turbo (Together)",
        context_length=131_072,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="low",
        is_local=False,
    ),
    ModelEntry(
        model_id="Qwen/Qwen2.5-72B-Instruct-Turbo",
        provider="together",
        display_name="Qwen2.5 72B Instruct Turbo (Together)",
        context_length=32_768,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="low",
        is_local=False,
    ),
    # ── Anthropic ─────────────────────────────────────────────────────────────
    ModelEntry(
        model_id="claude-3-5-haiku-20241022",
        provider="anthropic",
        display_name="Claude 3.5 Haiku",
        context_length=200_000,
        supports_tool_calling=True,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="low",
        is_local=False,
    ),
    ModelEntry(
        model_id="claude-3-5-sonnet-20241022",
        provider="anthropic",
        display_name="Claude 3.5 Sonnet",
        context_length=200_000,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="medium",
        is_local=False,
    ),
    ModelEntry(
        model_id="claude-opus-4-5",
        provider="anthropic",
        display_name="Claude Opus 4.5",
        context_length=200_000,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="high",
        is_local=False,
    ),
    # ── OpenAI ────────────────────────────────────────────────────────────────
    ModelEntry(
        model_id="gpt-4o-mini",
        provider="openai",
        display_name="GPT-4o Mini",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="low",
        is_local=False,
    ),
    ModelEntry(
        model_id="gpt-4o",
        provider="openai",
        display_name="GPT-4o",
        context_length=128_000,
        supports_tool_calling=True,
        supports_vision=True,
        supports_streaming=True,
        cost_tier="medium",
        is_local=False,
    ),
    ModelEntry(
        model_id="o3-mini",
        provider="openai",
        display_name="o3-mini",
        context_length=128_000,
        supports_tool_calling=False,
        supports_vision=False,
        supports_streaming=True,
        cost_tier="medium",
        is_local=False,
        metadata={"thinking_model": True},
    ),
    # ── Cerebras (free tier, fast inference) ──────────────────────────────────
    ModelEntry(
        model_id="openai/gpt-oss-120b",
        provider="cerebras",
        display_name="GPT-OSS 120B (Cerebras)",
        context_length=8_192,
        supports_tool_calling=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="llama3.1-8b",
        provider="cerebras",
        display_name="Llama 3.1 8B (Cerebras)",
        context_length=8_192,
        supports_tool_calling=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    # ── Cohere (shared 1000 req/month free tier) ───────────────────────────────
    ModelEntry(
        model_id="command-a-03-2025",
        provider="cohere",
        display_name="Command A (Cohere)",
        context_length=256_000,
        supports_tool_calling=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
    ModelEntry(
        model_id="command-r-plus-08-2024",
        provider="cohere",
        display_name="Command R+ (Cohere)",
        context_length=128_000,
        supports_tool_calling=True,
        supports_streaming=True,
        cost_tier="free",
        is_local=False,
    ),
]

#: Recommended Groq model IDs for multi-bucket rotation strategies.
#: List from fastest/cheapest to most capable.
GROQ_ROTATION_MODELS: list[str] = [
    "llama-3.1-8b-instant",
    "meta-llama/llama-4-scout-17b-16e-instruct",
    "llama3-8b-8192",
    "qwen/qwen3-32b",
    "llama-3.3-70b-versatile",
    "moonshotai/kimi-k2-instruct",
]

#: All Gemini model IDs registered with the ``models/`` prefix required by
#: the Google Gemini OpenAI-compatible endpoint.
GEMINI_MODELS: list[str] = [
    "models/gemini-2.5-flash",
    "models/gemini-2.5-pro",
    "models/gemini-2.0-flash",
    "models/gemini-2.0-flash-lite",
    # Gemini 1.5 models were removed by Google (404). Use ProviderModelDiscovery.for_google()
    # for current model list.
]
