#!/usr/bin/env python3
"""
Demo script showing PR Manager output examples.

Generates sample output to demonstrate the PR management tool's capabilities.
"""

print("=" * 80)
print("📊 TTA.dev PR Dashboard DEMO")
print("=" * 80)
print()
print("📈 Summary: 12 open PRs")
print()
print("🔴 CRITICAL (1)")
print("-" * 80)
print("  # 456 | P 95 |  3d | @contributor1    | Security: Fix authentication bypass")
print()
print("✅ READY-TO-MERGE (2)")
print("-" * 80)
print("  # 789 | P 85 |  5d | @contributor2    | feat: Add new caching primitive")
print("  # 123 | P 80 |  2d | @maintainer      | docs: Update API documentation")
print()
print("👀 NEEDS-REVIEW (4)")
print("-" * 80)
print("  # 234 | P 70 |  1d | @contributor3    | refactor: Improve error handling")
print("  # 345 | P 65 |  4d | @contributor4    | test: Add integration tests")
print("  # 567 | P 60 |  3d | @contributor5    | feat: Implement retry with jitter")
print("  # 890 | P 55 |  2d | @contributor6    | fix: Memory leak in router primitive")
print()
print("🔧 CHANGES-REQUESTED (2)")
print("-" * 80)
print("  # 901 | P 50 |  7d | @contributor7    | feat: Add circuit breaker primitive")
print("  # 112 | P 45 | 10d | @contributor8    | docs: Add architecture diagrams")
print()
print("🕸️ STALE (2)")
print("-" * 80)
print("  # 213 | P 35 | 15d | @contributor9    | chore: Update dependencies")
print("  # 314 | P 30 | 20d | @contributor10   | WIP: Experimental feature")
print()
print("📝 DRAFT (1)")
print("-" * 80)
print("  # 415 | P 25 |  5d | @contributor11   | Draft: New observability features")
print()
print("=" * 80)
print()
print()
print("=" * 80)
print("🔍 PR Analysis DEMO")
print("=" * 80)
print()
print("📅 Age Metrics:")
print("  Average age: 6.3 days")
print("  Oldest PR: 20 days")
print("  Newest PR: 1 days")
print()
print("💤 Activity Metrics:")
print("  Average staleness: 4.2 days")
print("  Stale PRs (7+ days): 2")
print()
print("👥 Review Status:")
print("  Approved: 2")
print("  Changes requested: 2")
print("  No review yet: 8")
print()
print("📝 Draft PRs: 1")
print()
print("📏 Size Metrics:")
print("  Total additions: 4,523")
print("  Total deletions: 1,234")
print("  Total files changed: 87")
print()
print("🎯 Priority Distribution:")
print("  High (70+): 5")
print("  Medium (40-69): 4")
print("  Low (<40): 3")
print()
print("=" * 80)
print()
print()
print("=" * 80)
print("💡 PR Recommendations DEMO")
print("=" * 80)
print()
print("🚀 Ready to Merge (2):")
print("  ✅ Merge PR #789: feat: Add new caching primitive")
print("  ✅ Merge PR #123: docs: Update API documentation")
print()
print("👀 Needs Review (4):")
print("  👥 Review PR #234: refactor: Improve error handling (1d old)")
print("  👥 Review PR #345: test: Add integration tests (4d old)")
print("  👥 Review PR #567: feat: Implement retry with jitter (3d old)")
print("  👥 Review PR #890: fix: Memory leak in router primitive (2d old)")
print()
print("🔧 Needs Changes (2):")
print("  📝 Follow up on PR #901: feat: Add circuit breaker primitive (waiting 7d)")
print("  📝 Follow up on PR #112: docs: Add architecture diagrams (waiting 10d)")
print()
print("🗑️ Consider Closing (1):")
print("  ⏹️ Close PR #314: WIP: Experimental feature (inactive 20d)")
print()
print("=" * 80)
print()
print("✨ Demo complete! Use 'python scripts/pr_manager.py <command>' for real data.")
