#!/bin/bash
# Setup Native Linux Observability Stack
# Replaces Docker-based Grafana/Prometheus with native Linux services

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
GRAFANA_CLOUD_TOKEN="${GRAFANA_CLOUD_TOKEN:-}"
GRAFANA_CLOUD_STACK="${GRAFANA_CLOUD_STACK:-theinterneti}"
GRAFANA_CLOUD_REGION="${GRAFANA_CLOUD_REGION:-prod-us-east-0}"
INSTALL_LOCAL_PROMETHEUS="${INSTALL_LOCAL_PROMETHEUS:-false}"
INSTALL_LOCAL_GRAFANA="${INSTALL_LOCAL_GRAFANA:-false}"

# Functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_os() {
    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        OS=$ID
        OS_VERSION=$VERSION_ID
    else
        log_error "Cannot detect OS. /etc/os-release not found."
        exit 1
    fi
    
    log_info "Detected OS: $OS $OS_VERSION"
}

check_requirements() {
    log_info "Checking requirements..."
    
    # Check if running with sudo
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run with sudo"
        exit 1
    fi
    
    # Check for required commands
    local required_cmds=("systemctl" "wget" "gpg")
    for cmd in "${required_cmds[@]}"; do
        if ! command -v "$cmd" &> /dev/null; then
            log_error "Required command not found: $cmd"
            exit 1
        fi
    done
    
    log_info "All requirements met"
}

load_env_file() {
    local env_file="${HOME}/.env.tta-dev"
    if [[ -f "$env_file" ]]; then
        log_info "Loading Grafana Cloud credentials from $env_file"
        # Source env file
        set -a
        source "$env_file"
        set +a
        
        # Extract token if present
        if [[ -n "${GRAFANA_CLOUD_API_KEY:-}" ]]; then
            GRAFANA_CLOUD_TOKEN="$GRAFANA_CLOUD_API_KEY"
        fi
    else
        log_warn "Environment file not found: $env_file"
    fi
}

setup_grafana_repo_debian() {
    log_info "Setting up Grafana APT repository..."
    
    # Install GPG if not present
    if ! command -v gpg &> /dev/null; then
        apt-get update
        apt-get install -y gpg
    fi
    
    # Add Grafana repository
    mkdir -p /etc/apt/keyrings/
    wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | tee /etc/apt/keyrings/grafana.gpg > /dev/null
    echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | tee /etc/apt/sources.list.d/grafana.list
    
    apt-get update
    log_info "Grafana repository added successfully"
}

setup_grafana_repo_rhel() {
    log_info "Setting up Grafana YUM repository..."
    
    wget -q -O gpg.key https://rpm.grafana.com/gpg.key
    rpm --import gpg.key
    
    cat > /etc/yum.repos.d/grafana.repo <<EOF
[grafana]
name=grafana
baseurl=https://rpm.grafana.com
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://rpm.grafana.com/gpg.key
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
EOF
    
    log_info "Grafana repository added successfully"
}

install_alloy() {
    log_info "Installing Grafana Alloy..."
    
    case "$OS" in
        ubuntu|debian)
            apt-get install -y alloy
            ;;
        rhel|fedora|centos)
            dnf install -y alloy
            ;;
        *)
            log_error "Unsupported OS: $OS"
            exit 1
            ;;
    esac
    
    # Verify installation
    if command -v alloy &> /dev/null; then
        local version=$(alloy --version | head -n1)
        log_info "Grafana Alloy installed: $version"
    else
        log_error "Alloy installation failed"
        exit 1
    fi
}

configure_alloy_env() {
    log_info "Configuring Alloy environment..."
    
    if [[ -z "$GRAFANA_CLOUD_TOKEN" ]]; then
        log_error "GRAFANA_CLOUD_TOKEN is not set"
        log_error "Please set it in ~/.env.tta-dev or export it before running this script"
        exit 1
    fi
    
    # Create environment file
    cat > /etc/default/alloy <<EOF
# Grafana Cloud Configuration
# Generated by setup-native-observability.sh on $(date)

GRAFANA_CLOUD_TOKEN="${GRAFANA_CLOUD_TOKEN}"
GRAFANA_CLOUD_STACK="${GRAFANA_CLOUD_STACK}"
GRAFANA_CLOUD_REGION="${GRAFANA_CLOUD_REGION}"

# Custom arguments for Alloy
CUSTOM_ARGS=""
CONFIG_FILE="/etc/alloy/config.alloy"

# Restart on system upgrade
RESTART_ON_UPGRADE=true
EOF
    
    chmod 600 /etc/default/alloy
    log_info "Alloy environment configured at /etc/default/alloy"
}

configure_alloy_config() {
    log_info "Creating Alloy configuration..."
    
    mkdir -p /etc/alloy
    
    cat > /etc/alloy/config.alloy <<'EOF'
// Grafana Alloy Configuration for TTA.dev
// Collects metrics, logs, and traces and ships to Grafana Cloud

// Prometheus metrics scraping from TTA.dev application
prometheus.scrape "tta_app" {
  targets = [{
    __address__ = "localhost:9464",
    job = "tta-dev-app",
  }]
  forward_to = [prometheus.remote_write.grafana_cloud.receiver]
  scrape_interval = "15s"
  scrape_timeout = "10s"
}

// Remote write to Grafana Cloud Prometheus
prometheus.remote_write "grafana_cloud" {
  endpoint {
    url = "https://prometheus-" + env("GRAFANA_CLOUD_REGION") + ".grafana.net/api/prom/push"
    
    basic_auth {
      username = env("GRAFANA_CLOUD_STACK")
      password = env("GRAFANA_CLOUD_TOKEN")
    }
    
    queue_config {
      capacity = 10000
      max_shards = 10
    }
  }
}

// Systemd journal logs collection
loki.source.journal "system_logs" {
  max_age = "24h"
  forward_to = [loki.process.tta_filter.receiver]
  
  labels = {
    job = "systemd-journal",
    host = env("HOSTNAME"),
  }
}

// Filter and process logs
loki.process "tta_filter" {
  forward_to = [loki.write.grafana_cloud.receiver]
  
  // Extract log level
  stage.regex {
    expression = "level=(?P<level>\\w+)"
  }
  
  stage.labels {
    values = {
      level = "",
    }
  }
}

// Loki logs to Grafana Cloud
loki.write "grafana_cloud" {
  endpoint {
    url = "https://logs-" + env("GRAFANA_CLOUD_REGION") + ".grafana.net/loki/api/v1/push"
    
    basic_auth {
      username = env("GRAFANA_CLOUD_STACK")
      password = env("GRAFANA_CLOUD_TOKEN")
    }
  }
}

// OTLP receiver for traces (OpenTelemetry)
otelcol.receiver.otlp "default" {
  grpc {
    endpoint = "0.0.0.0:4317"
  }
  
  http {
    endpoint = "0.0.0.0:4318"
  }
  
  output {
    traces = [otelcol.exporter.otlp.grafana_cloud.input]
  }
}

// Basic auth component for Tempo
otelcol.auth.basic "grafana_cloud" {
  username = env("GRAFANA_CLOUD_STACK")
  password = env("GRAFANA_CLOUD_TOKEN")
}

// Traces to Grafana Cloud Tempo
otelcol.exporter.otlp "grafana_cloud" {
  client {
    endpoint = "tempo-" + env("GRAFANA_CLOUD_REGION") + ".grafana.net:443"
    auth = otelcol.auth.basic.grafana_cloud.handler
  }
}
EOF
    
    chmod 644 /etc/alloy/config.alloy
    log_info "Alloy configuration created at /etc/alloy/config.alloy"
}

start_alloy_service() {
    log_info "Starting Grafana Alloy service..."
    
    # Reload systemd
    systemctl daemon-reload
    
    # Enable Alloy service
    systemctl enable alloy
    
    # Start Alloy service
    systemctl start alloy
    
    # Check status
    if systemctl is-active --quiet alloy; then
        log_info "Grafana Alloy service started successfully"
    else
        log_error "Failed to start Grafana Alloy service"
        log_error "Check logs with: journalctl -u alloy -n 50"
        exit 1
    fi
}

verify_alloy() {
    log_info "Verifying Alloy installation..."
    
    # Wait a few seconds for service to start
    sleep 3
    
    # Check if metrics endpoint is accessible
    if curl -sf http://localhost:12345/metrics > /dev/null; then
        log_info "Alloy metrics endpoint is accessible"
    else
        log_warn "Cannot access Alloy metrics endpoint at http://localhost:12345/metrics"
    fi
    
    # Check service status
    if systemctl is-active --quiet alloy; then
        log_info "Alloy service is running"
        
        # Show recent logs
        echo ""
        log_info "Recent Alloy logs:"
        journalctl -u alloy -n 10 --no-pager
    else
        log_error "Alloy service is not running"
        exit 1
    fi
}

install_local_prometheus() {
    if [[ "$INSTALL_LOCAL_PROMETHEUS" != "true" ]]; then
        return
    fi
    
    log_info "Installing local Prometheus..."
    
    local version="2.48.1"
    local arch="linux-amd64"
    local url="https://github.com/prometheus/prometheus/releases/download/v${version}/prometheus-${version}.${arch}.tar.gz"
    
    # Download and extract
    cd /tmp
    wget -q "$url"
    tar xzf "prometheus-${version}.${arch}.tar.gz"
    cd "prometheus-${version}.${arch}"
    
    # Install binaries
    cp prometheus promtool /usr/local/bin/
    
    # Create user
    if ! id prometheus &>/dev/null; then
        useradd --no-create-home --shell /bin/false prometheus
    fi
    
    # Create directories
    mkdir -p /etc/prometheus /var/lib/prometheus
    chown -R prometheus:prometheus /etc/prometheus /var/lib/prometheus
    
    # Create configuration
    cat > /etc/prometheus/prometheus.yml <<EOF
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tta-dev-app'
    static_configs:
      - targets: ['localhost:9464']
    scrape_interval: 15s
EOF
    
    chown prometheus:prometheus /etc/prometheus/prometheus.yml
    
    # Create systemd service
    cat > /etc/systemd/system/prometheus.service <<EOF
[Unit]
Description=Prometheus Monitoring System
Documentation=https://prometheus.io/docs/
Wants=network-online.target
After=network-online.target

[Service]
User=prometheus
Group=prometheus
Type=simple
ExecStart=/usr/local/bin/prometheus \\
  --config.file=/etc/prometheus/prometheus.yml \\
  --storage.tsdb.path=/var/lib/prometheus/ \\
  --web.console.libraries=/usr/share/prometheus/console_libraries \\
  --web.console.templates=/usr/share/prometheus/consoles

[Install]
WantedBy=multi-user.target
EOF
    
    # Start service
    systemctl daemon-reload
    systemctl enable prometheus
    systemctl start prometheus
    
    if systemctl is-active --quiet prometheus; then
        log_info "Local Prometheus installed and running at http://localhost:9090"
    else
        log_warn "Prometheus installation completed but service is not running"
    fi
    
    # Cleanup
    cd /
    rm -rf /tmp/prometheus-*
}

install_local_grafana() {
    if [[ "$INSTALL_LOCAL_GRAFANA" != "true" ]]; then
        return
    fi
    
    log_info "Installing local Grafana..."
    
    case "$OS" in
        ubuntu|debian)
            apt-get install -y grafana
            ;;
        rhel|fedora|centos)
            dnf install -y grafana
            ;;
        *)
            log_error "Unsupported OS: $OS"
            exit 1
            ;;
    esac
    
    # Start service
    systemctl enable grafana-server
    systemctl start grafana-server
    
    if systemctl is-active --quiet grafana-server; then
        log_info "Local Grafana installed and running at http://localhost:3000"
        log_info "Default credentials: admin/admin"
    else
        log_warn "Grafana installation completed but service is not running"
    fi
}

print_summary() {
    echo ""
    log_info "===== Installation Complete ====="
    echo ""
    log_info "Grafana Alloy is now running and shipping telemetry to Grafana Cloud"
    echo ""
    log_info "Services:"
    log_info "  - Grafana Alloy: systemctl status alloy"
    log_info "  - Alloy metrics: http://localhost:12345/metrics"
    
    if [[ "$INSTALL_LOCAL_PROMETHEUS" == "true" ]]; then
        log_info "  - Local Prometheus: http://localhost:9090"
    fi
    
    if [[ "$INSTALL_LOCAL_GRAFANA" == "true" ]]; then
        log_info "  - Local Grafana: http://localhost:3000"
    fi
    
    echo ""
    log_info "Grafana Cloud:"
    log_info "  - Dashboard: https://${GRAFANA_CLOUD_STACK}.grafana.net/"
    echo ""
    log_info "Next steps:"
    log_info "  1. Verify metrics in Grafana Cloud"
    log_info "  2. Check Alloy logs: journalctl -u alloy -f"
    log_info "  3. Test your TTA.dev app exports metrics on port 9464"
    echo ""
    log_info "Documentation: docs/guides/LINUX_NATIVE_OBSERVABILITY.md"
    echo ""
}

# Main installation flow
main() {
    log_info "Starting Native Linux Observability Setup"
    echo ""
    
    check_os
    check_requirements
    load_env_file
    
    # Setup repository based on OS
    case "$OS" in
        ubuntu|debian)
            setup_grafana_repo_debian
            ;;
        rhel|fedora|centos)
            setup_grafana_repo_rhel
            ;;
        *)
            log_error "Unsupported OS: $OS"
            exit 1
            ;;
    esac
    
    # Install and configure Alloy
    install_alloy
    configure_alloy_env
    configure_alloy_config
    start_alloy_service
    verify_alloy
    
    # Optional: Install local services
    install_local_prometheus
    install_local_grafana
    
    print_summary
}

# Run main function
main "$@"
