#!/bin/bash
# Initialize coordination infrastructure for TTA.dev worktree system

set -e

ORCHESTRATOR="/home/thein/repos/TTA.dev"
WORKTREES=(
    "TTA.dev-augment"
    "TTA.dev-cline"
    "TTA.dev-copilot"
)

echo "🚀 Initializing TTA.dev Worktree Coordination System"
echo "======================================================="
echo

# 1. Setup orchestrator coordination directory
echo "📁 Setting up orchestrator coordination directory..."
cd "$ORCHESTRATOR"

mkdir -p .worktree/coordination/{agent-augment,agent-cline,agent-copilot,integration-queue}
echo "  ✓ Created coordination directories"

# 2. Create shared Logseq KB structure
echo "📚 Setting up shared Logseq knowledge base..."
mkdir -p logseq/shared/pages/{Worktree\ Patterns,Cross-Agent\ Learnings,Integration\ Decisions}
echo "  ✓ Created shared KB directories"

# 3. Create coordination dashboard template
cat > logseq/shared/coordination-dashboard.md << 'EOF'
# Worktree Coordination Dashboard

**Last Updated:** Auto-generated by coordination scripts

## Active Worktrees

- [[TTA.dev]] (orchestrator) - `experimental/workflow-agent-integrations`
- [[TTA.dev-augment]] - `agent/augment`
- [[TTA.dev-cline]] - `experimental/issue-collaboration`
- [[TTA.dev-copilot]] - `agent/copilot`

## Pending Pattern Reviews

Check: `.worktree/coordination/agent-*/`

Run: `python scripts/worktree/coordination-status.py`

## Integration Queue

Check: `.worktree/coordination/integration-queue/`

## Quick Actions

```bash
# Sync all agents
python scripts/worktree/sync-learnings.py --sync-all

# Check status
python scripts/worktree/coordination-status.py

# Sync specific agent
python scripts/worktree/sync-learnings.py --from augment
```

## Tagging Guide

- `#local-pattern` - Pattern discovered locally (not yet shared)
- `#ready-to-share` - Pattern ready for orchestrator review
- `#under-review` - Pattern being evaluated by orchestrator
- `#approved-pattern` - Pattern validated for sharing
- `#integration-pending` - Pattern queued for integration
- `#integrated` - Pattern applied across worktrees
EOF
echo "  ✓ Created coordination dashboard"

# 4. Setup agent worktrees
echo "🔧 Setting up agent worktrees..."
for worktree in "${WORKTREES[@]}"; do
    worktree_path="/home/thein/repos/$worktree"
    
    if [ ! -d "$worktree_path" ]; then
        echo "  ⚠ Worktree not found: $worktree_path (skipping)"
        continue
    fi
    
    echo "  📦 Setting up $worktree..."
    
    # Create .worktree directory structure
    cd "$worktree_path"
    mkdir -p .worktree/local-patterns
    mkdir -p .worktree/experiments
    mkdir -p .worktree/session-logs
    
    # Create agent config template
    cat > .worktree/agent-config.yml << 'EOF'
# Agent-specific configuration
agent_name: AGENT_NAME
role: AGENT_ROLE
sync_enabled: true
auto_tag_patterns: true

# Pattern sharing preferences
share_preferences:
  auto_share_high_impact: true
  require_review_before_share: false
  
# Integration preferences
integration_preferences:
  accept_auto_integrate: false
  review_all_integrations: true
EOF
    
    # Link shared KB (symlink)
    if [ ! -L "logseq/shared" ]; then
        mkdir -p logseq
        ln -s "$ORCHESTRATOR/logseq/shared" logseq/shared
        echo "    ✓ Linked shared KB"
    fi
    
    # Add .worktree to .gitignore if not already there
    if [ -f .gitignore ]; then
        if ! grep -q "^.worktree/$" .gitignore; then
            echo ".worktree/" >> .gitignore
            echo "    ✓ Added .worktree/ to .gitignore"
        fi
    else
        echo ".worktree/" > .gitignore
        echo "    ✓ Created .gitignore with .worktree/"
    fi
    
    echo "    ✓ Setup complete for $worktree"
done

# 5. Make scripts executable
echo "🔐 Making coordination scripts executable..."
cd "$ORCHESTRATOR"
chmod +x scripts/worktree/*.py
chmod +x scripts/worktree/*.sh
echo "  ✓ Scripts are executable"

# 6. Create initial sync status
echo "💾 Initializing sync status..."
cat > .worktree/sync-status.json << EOF
{
  "initialized": "$(date -u +%Y-%m-%dT%H:%M:%S)Z",
  "last_sync": null,
  "agents": {}
}
EOF
echo "  ✓ Created sync status file"

# 7. Summary
echo
echo "✅ Worktree Coordination System Initialized!"
echo "=============================================="
echo
echo "Next steps:"
echo "  1. Run: python scripts/worktree/coordination-status.py"
echo "  2. Run: python scripts/worktree/sync-learnings.py --sync-all"
echo "  3. Open: logseq/shared/coordination-dashboard.md in Logseq"
echo
echo "Documentation:"
echo "  - WORKTREE_COORDINATION_PROTOCOL.md"
echo "  - scripts/worktree/README.md"
echo
