name: '🧪 Gemini Test - Minimal'

on:
  issue_comment:
    types:
      - 'created'

jobs:
  test:
    if: |-
      github.event.sender.type == 'User' &&
      startsWith(github.event.comment.body, '@gemini-test') &&
      contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      issues: 'write'
    steps:
      - name: 'Run Gemini CLI (Minimal)'
        uses: 'google-github-actions/run-gemini-cli@v0'
        env:
          GITHUB_TOKEN: '${{ github.token }}'
        with:
          gemini_api_key: '${{ secrets.GEMINI_API_KEY }}'
          gemini_model: 'gemini-1.5-flash'
          gemini_debug: true
          settings: |-
            {
              "model": {
                "maxSessionTurns": 5
              },
              "telemetry": {
                "enabled": false
              }
            }
          prompt: |-
            You are a helpful assistant. Respond to the user's request briefly and clearly.
            
            User request: ${{ github.event.comment.body }}
